/**
 * AI-Generated Website Detector
 * ------------------------------
 * Heuristic engine that scores how "standard / AI-generated" a website looks
 * on a 0-100 scale. Higher = more cookie-cutter (the kind of site a coding
 * agent + default skills spits out with zero customisation).
 *
 * The thesis: AI builders (Claude Code, v0, Lovable, Bolt, Cursor, Framer AI)
 * and their default component libraries produce a recognisable "house style".
 * We fingerprint that house style across several weighted signal categories.
 *
 * Everything runs on the raw server-fetched HTML + response headers. No JS is
 * rendered, which is fine — a heavy client-only bundle with an empty shell is
 * itself a tell.
 */

export type SignalCategory =
  | "watermark"
  | "stack"
  | "copy"
  | "structure"
  | "visual"
  | "placeholder";

export interface Signal {
  id: string;
  label: string;
  category: SignalCategory;
  points: number; // contribution toward the 0-100 score
  evidence: string[]; // human-readable proof, trimmed
}

export interface CategoryScore {
  category: SignalCategory;
  title: string;
  emoji: string;
  points: number;
  max: number;
  signals: Signal[];
}

export interface AnalysisResult {
  url: string;
  finalUrl: string;
  score: number; // 0-100, higher = more AI-generated/standard
  verdict: Verdict;
  categories: CategoryScore[];
  topSignals: Signal[];
  meta: {
    title: string | null;
    generator: string | null;
    bytes: number;
    fetchedAt: string;
  };
}

export interface Verdict {
  label: string;
  blurb: string;
  emoji: string;
}

const CATEGORY_META: Record<
  SignalCategory,
  { title: string; emoji: string; max: number }
> = {
  watermark: { title: "Builder Watermarks", emoji: "🏷️", max: 35 },
  stack: { title: "Default Stack Fingerprints", emoji: "🧱", max: 22 },
  copy: { title: "AI Copywriting Tells", emoji: "✍️", max: 24 },
  structure: { title: "Structural Clichés", emoji: "📐", max: 16 },
  visual: { title: "Visual Defaults", emoji: "🎨", max: 16 },
  placeholder: { title: "Placeholder Residue", emoji: "🚧", max: 12 },
};

/** Clamp + dedupe + trim a list of evidence strings. */
function ev(matches: string[], limit = 4): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const m of matches) {
    const t = m.replace(/\s+/g, " ").trim().slice(0, 80);
    if (t && !seen.has(t.toLowerCase())) {
      seen.add(t.toLowerCase());
      out.push(t);
    }
    if (out.length >= limit) break;
  }
  return out;
}

function countMatches(haystack: string, re: RegExp): RegExpMatchArray[] {
  return [...haystack.matchAll(re)];
}

/**
 * The detector registry. Each detector inspects the page and may emit a Signal.
 * Detectors are pure: (ctx) => Signal | null.
 */
interface Ctx {
  html: string;
  lower: string;
  text: string; // visible-ish text, tags stripped
  headers: Record<string, string>;
  url: string;
}

type Detector = (ctx: Ctx) => Signal | null;

/* ------------------------------------------------------------------ *
 * 1. BUILDER WATERMARKS — the strongest, highest-confidence signals.
 * ------------------------------------------------------------------ */

const watermarkDetectors: Detector[] = [
  (c) => {
    // Explicit AI site-builder fingerprints.
    const builders: { name: string; re: RegExp; pts: number }[] = [
      { name: "v0 by Vercel", re: /v0\.dev|v0-[a-z0-9]+\.vercel|generated by v0/i, pts: 22 },
      { name: "Lovable", re: /lovable\.dev|lovable-tagger|gpt-?engineer|gptengineer/i, pts: 22 },
      { name: "Bolt.new", re: /bolt\.new|stackblitz\.com\/edit|bolt-/i, pts: 20 },
      { name: "Framer", re: /framerusercontent\.com|data-framer-|framer\.(com|website)|generator"\s*content="Framer/i, pts: 18 },
      { name: "Webflow", re: /webflow\.(io|com)|wf-|data-wf-/i, pts: 16 },
      { name: "Wix", re: /wix\.com|wixstatic|_wixCssState/i, pts: 14 },
      { name: "Durable AI", re: /durable\.co/i, pts: 18 },
      { name: "Replit Agent", re: /replit\.dev|replit\.app/i, pts: 14 },
    ];
    const hits: string[] = [];
    let pts = 0;
    for (const b of builders) {
      if (b.re.test(c.html)) {
        hits.push(b.name);
        pts = Math.max(pts, b.pts); // strongest single builder, don't stack fully
      }
    }
    if (!hits.length) return null;
    return {
      id: "ai-builder",
      label: `Built with a known AI/no-code builder: ${hits.join(", ")}`,
      category: "watermark",
      points: pts,
      evidence: ev(hits),
    };
  },

  (c) => {
    // <meta name="generator">
    const m = c.html.match(/<meta[^>]+name=["']generator["'][^>]+content=["']([^"']+)["']/i);
    if (!m) return null;
    const gen = m[1];
    const strong = /next\.?js|gatsby|hugo|astro|wordpress|framer|webflow|wix|squarespace/i.test(gen);
    return {
      id: "generator-meta",
      label: `Declares generator: "${gen}"`,
      category: "watermark",
      points: strong ? 8 : 4,
      evidence: ev([gen]),
    };
  },

  (c) => {
    // Next.js default stack signatures (the agent default).
    const tells: string[] = [];
    if (/\/_next\/static\//.test(c.html)) tells.push("/_next/static/ assets");
    if (/__NEXT_DATA__/.test(c.html)) tells.push("__NEXT_DATA__ payload");
    if (/self\.__next_f/.test(c.html)) tells.push("Next.js RSC stream (__next_f)");
    if ((c.headers["x-powered-by"] || "").toLowerCase().includes("next")) tells.push("x-powered-by: Next.js");
    if (!tells.length) return null;
    return {
      id: "nextjs",
      label: "Next.js — the default framework coding agents reach for",
      category: "watermark",
      points: Math.min(12, 5 + tells.length * 2),
      evidence: ev(tells),
    };
  },

  (c) => {
    // Vercel hosting (overwhelmingly the agent default deploy target).
    const tells: string[] = [];
    if (c.headers["x-vercel-id"]) tells.push("x-vercel-id header");
    if (/x-vercel/i.test(JSON.stringify(c.headers))) tells.push("vercel edge headers");
    if ((c.headers["server"] || "").toLowerCase().includes("vercel")) tells.push("server: Vercel");
    if (!tells.length) return null;
    return {
      id: "vercel",
      label: "Hosted on Vercel (default agent deploy target)",
      category: "watermark",
      points: 6,
      evidence: ev(tells),
    };
  },

  (c) => {
    // "Made with / Built with" badges left in the markup.
    const m = countMatches(
      c.text,
      /\b(made|built|created|powered)\s+(with|by|using)\s+(v0|lovable|bolt|framer|webflow|wix|claude|cursor|replit|durable)\b/gi
    );
    if (!m.length) return null;
    return {
      id: "made-with-badge",
      label: "Leftover “Made with …” builder badge in the page",
      category: "watermark",
      points: 10,
      evidence: ev(m.map((x) => x[0])),
    };
  },
];

/* ------------------------------------------------------------------ *
 * 2. DEFAULT STACK FINGERPRINTS — Tailwind + shadcn/ui + Lucide + Geist.
 * ------------------------------------------------------------------ */

const stackDetectors: Detector[] = [
  (c) => {
    // Tailwind utility-class density.
    const utils = countMatches(
      c.html,
      /\bclass(?:Name)?=["'][^"']*\b(?:flex|grid|gap-\d|px-\d|py-\d|mx-auto|rounded-(?:lg|xl|2xl|3xl|full)|text-(?:sm|lg|xl|2xl|3xl|4xl|5xl|6xl)|font-(?:medium|semibold|bold)|items-center|justify-(?:center|between)|space-y-\d|tracking-tight|leading-)/g
    );
    if (utils.length < 6) return null;
    const pts = Math.min(8, 3 + Math.floor(utils.length / 12));
    return {
      id: "tailwind",
      label: "Tailwind CSS utility-class soup (the agent default styling)",
      category: "stack",
      points: pts,
      evidence: ev([`${utils.length} Tailwind-style utility classes detected`]),
    };
  },

  (c) => {
    // shadcn/ui component fingerprints.
    const tells: string[] = [];
    if (/data-slot=/.test(c.html)) tells.push("data-slot attributes");
    if (/bg-(?:primary|secondary|muted|accent|destructive)\b/.test(c.html)) tells.push("bg-primary / muted tokens");
    if (/text-(?:primary|muted)-foreground/.test(c.html)) tells.push("*-foreground color tokens");
    if (/inline-flex items-center justify-center (?:gap-2 )?whitespace-nowrap rounded-md/.test(c.html))
      tells.push("canonical shadcn Button classes");
    if (/border-input|ring-offset-background|focus-visible:ring-/.test(c.html)) tells.push("shadcn focus-ring tokens");
    if (tells.length < 1) return null;
    return {
      id: "shadcn",
      label: "shadcn/ui components used verbatim (zero theme customisation)",
      category: "stack",
      points: Math.min(9, 3 + tells.length * 2),
      evidence: ev(tells),
    };
  },

  (c) => {
    // Lucide icons — shadcn's default icon set.
    const m = countMatches(c.html, /lucide(?:-react)?|class=["'][^"']*\blucide\b/gi);
    if (!m.length) return null;
    return {
      id: "lucide",
      label: "Lucide icons (shadcn's default icon set, untouched)",
      category: "stack",
      points: 4,
      evidence: ev([`${m.length} Lucide references`]),
    };
  },

  (c) => {
    // Default fonts: Geist (Vercel) / Inter.
    const tells: string[] = [];
    if (/--font-geist|geist(?:-sans|-mono)?/i.test(c.html)) tells.push("Geist (Next.js default)");
    if (/fonts\.googleapis\.com[^"']*Inter|font-inter|"Inter"/i.test(c.html)) tells.push("Inter");
    if (!tells.length) return null;
    return {
      id: "default-fonts",
      label: "Default agent fonts (Geist / Inter), no custom typography",
      category: "stack",
      points: 4,
      evidence: ev(tells),
    };
  },
];

/* ------------------------------------------------------------------ *
 * 3. AI COPYWRITING TELLS — the LLM voice.
 * ------------------------------------------------------------------ */

const AI_BUZZWORDS = [
  "seamless", "seamlessly", "effortless", "effortlessly", "elevate", "supercharge",
  "unlock", "unleash", "harness", "leverage", "robust", "cutting-edge", "game-changer",
  "game-changing", "revolutionize", "revolutionise", "transform your", "take your",
  "next level", "empower", "streamline", "boost your", "skyrocket", "delve",
  "in today's", "fast-paced", "ever-evolving", "the future of", "say goodbye to",
  "whether you're", "trusted by thousands", "join thousands", "powerful and intuitive",
  "intuitive and powerful", "tailored to your", "at your fingertips", "world-class",
];

const copyDetectors: Detector[] = [
  (c) => {
    const hits: string[] = [];
    for (const w of AI_BUZZWORDS) {
      const re = new RegExp(`\\b${w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "gi");
      const m = c.text.match(re);
      if (m) hits.push(...m);
    }
    if (hits.length < 1) return null;
    const unique = new Set(hits.map((h) => h.toLowerCase())).size;
    const pts = Math.min(12, unique * 2);
    return {
      id: "buzzwords",
      label: `LLM marketing buzzwords (${hits.length} hits across ${unique} phrases)`,
      category: "copy",
      points: pts,
      evidence: ev(hits, 6),
    };
  },

  (c) => {
    // "It's not just X, it's Y" — the signature LLM rhetorical move.
    const m = countMatches(c.text, /\b(?:it'?s|this is|we'?re)\s+not\s+just\s+[^.,;]{2,40}[,—-]\s*(?:it'?s|but|it is)\b/gi);
    if (!m.length) return null;
    return {
      id: "not-just",
      label: "“It's not just X, it's Y” — the signature LLM rhetorical tic",
      category: "copy",
      points: 6,
      evidence: ev(m.map((x) => x[0])),
    };
  },

  (c) => {
    // Em-dash density (LLMs adore the em-dash).
    const dashes = countMatches(c.text, /—|&mdash;|&#8212;/g).length;
    const per1k = c.text.length ? (dashes / c.text.length) * 1000 : 0;
    if (dashes < 3 || per1k < 0.4) return null;
    return {
      id: "em-dash",
      label: `Heavy em-dash usage (${dashes} em-dashes — a classic LLM tell)`,
      category: "copy",
      points: Math.min(6, 2 + Math.floor(per1k)),
      evidence: ev([`${dashes} em-dashes, ${per1k.toFixed(1)} per 1k chars`]),
    };
  },

  (c) => {
    // Generic CTAs.
    const m = countMatches(
      c.text,
      /\b(get started(?:\s+for free)?|start your free trial|get started today|sign up free|join (?:the )?waitlist|try it free|start building)\b/gi
    );
    if (m.length < 1) return null;
    return {
      id: "generic-cta",
      label: "Boilerplate CTAs (“Get Started” / “Start your free trial”)",
      category: "copy",
      points: Math.min(4, m.length * 2),
      evidence: ev(m.map((x) => x[0])),
    };
  },

  (c) => {
    // Tricolon punchy taglines: "Fast. Simple. Powerful."
    const m = countMatches(c.text, /\b([A-Z][a-z]{2,12})\.\s([A-Z][a-z]{2,12})\.\s([A-Z][a-z]{2,12})\./g);
    if (!m.length) return null;
    return {
      id: "tricolon",
      label: "Punchy three-word tricolon taglines (“Fast. Simple. Powerful.”)",
      category: "copy",
      points: 3,
      evidence: ev(m.map((x) => x[0])),
    };
  },
];

/* ------------------------------------------------------------------ *
 * 4. STRUCTURAL CLICHÉS — the canonical landing-page skeleton.
 * ------------------------------------------------------------------ */

const structureDetectors: Detector[] = [
  (c) => {
    const sections: string[] = [];
    if (/\b(features?)\b/i.test(c.text) && /grid|flex/.test(c.html)) sections.push("Features grid");
    if (/\btestimonials?\b|what (?:our|people) (?:say|love)|loved by/i.test(c.text)) sections.push("Testimonials");
    if (/\bpricing\b|\/month|per month|free\s+plan|pro\s+plan/i.test(c.text)) sections.push("Pricing tiers");
    if (/\bfrequently asked questions\b|\bfaq\b/i.test(c.text)) sections.push("FAQ");
    if (/trusted by|backed by|as seen (?:in|on)|powering/i.test(c.text)) sections.push("Logo cloud");
    if (sections.length < 2) return null;
    return {
      id: "landing-skeleton",
      label: `Canonical landing-page skeleton (${sections.length} stock sections)`,
      category: "structure",
      points: Math.min(8, sections.length * 2),
      evidence: ev(sections),
    };
  },

  (c) => {
    // Emoji in headings.
    const headings = countMatches(c.html, /<h[1-3][^>]*>([^<]*[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}][^<]*)<\/h[1-3]>/giu);
    if (!headings.length) return null;
    return {
      id: "emoji-headings",
      label: "Emoji-decorated section headings",
      category: "structure",
      points: 3,
      evidence: ev(headings.map((x) => x[1])),
    };
  },

  (c) => {
    // Repeated 3-card feature blocks (icon + h3 + p, ×3).
    const cards = countMatches(
      c.html,
      /<div[^>]*class(?:Name)?=["'][^"']*(?:rounded-(?:lg|xl|2xl)|border|shadow)[^"']*["'][^>]*>/gi
    ).length;
    if (cards < 3) return null;
    return {
      id: "card-grid",
      label: `Repeated rounded/shadow card blocks (×${cards}) — the feature-grid cliché`,
      category: "structure",
      points: Math.min(5, 2 + Math.floor(cards / 4)),
      evidence: ev([`${cards} card-style containers`]),
    };
  },
];

/* ------------------------------------------------------------------ *
 * 5. VISUAL DEFAULTS — the purple gradient + glass aesthetic.
 * ------------------------------------------------------------------ */

const visualDetectors: Detector[] = [
  (c) => {
    const m = countMatches(c.html, /bg-gradient-to-[a-z]+|from-(?:purple|indigo|violet|blue|fuchsia|pink|cyan)-\d|to-(?:purple|indigo|violet|blue|fuchsia|pink|cyan)-\d|linear-gradient/gi);
    if (!m.length) return null;
    const purple = /(?:from|to|via)-(?:purple|indigo|violet|fuchsia)/i.test(c.html);
    return {
      id: "gradients",
      label: purple
        ? "The default purple/indigo→blue gradient (peak AI aesthetic)"
        : "Heavy gradient usage",
      category: "visual",
      points: Math.min(7, (purple ? 4 : 2) + Math.floor(m.length / 4)),
      evidence: ev(m.map((x) => x[0])),
    };
  },

  (c) => {
    // Gradient clip-text headlines.
    const m = countMatches(c.html, /bg-clip-text\s+text-transparent|text-transparent\s+bg-clip-text|-webkit-background-clip:\s*text/gi);
    if (!m.length) return null;
    return {
      id: "gradient-text",
      label: "Gradient clip-text headline (the obligatory AI hero treatment)",
      category: "visual",
      points: 4,
      evidence: ev([`${m.length} gradient-text element(s)`]),
    };
  },

  (c) => {
    // Glassmorphism / heavy rounding.
    const tells: string[] = [];
    if (/backdrop-blur|backdrop-filter:\s*blur/i.test(c.html)) tells.push("backdrop-blur glass");
    if (/bg-white\/\d|bg-black\/\d|bg-opacity-/i.test(c.html)) tells.push("translucent panels");
    if (/rounded-(?:2xl|3xl|full)/.test(c.html)) tells.push("rounded-2xl/3xl");
    if (tells.length < 2) return null;
    return {
      id: "glass",
      label: "Glassmorphism + heavy rounded corners (default agent styling)",
      category: "visual",
      points: Math.min(5, tells.length * 2),
      evidence: ev(tells),
    };
  },
];

/* ------------------------------------------------------------------ *
 * 6. PLACEHOLDER RESIDUE — the "didn't even fill it in" tells.
 * ------------------------------------------------------------------ */

const placeholderDetectors: Detector[] = [
  (c) => {
    const m = countMatches(c.text, /\blorem ipsum\b|\bdolor sit amet\b/gi);
    if (!m.length) return null;
    return {
      id: "lorem",
      label: "Lorem ipsum placeholder copy still in place",
      category: "placeholder",
      points: 6,
      evidence: ev(m.map((x) => x[0])),
    };
  },

  (c) => {
    const m = countMatches(
      c.html,
      /your-?(?:email|name|company|domain)@|example\.com|youremail@|john\s?doe|jane\s?doe|name@example|hello@example|acme\s?(?:inc|corp)/gi
    );
    if (!m.length) return null;
    return {
      id: "placeholder-data",
      label: "Placeholder contact data (example.com / John Doe / Acme Inc)",
      category: "placeholder",
      points: Math.min(4, m.length + 1),
      evidence: ev(m.map((x) => x[0])),
    };
  },

  (c) => {
    const tells: string[] = [];
    if (/placehold\.(?:co|it)|via\.placeholder|placekitten|picsum\.photos|dummyimage/i.test(c.html))
      tells.push("placeholder image service");
    if (/images\.unsplash\.com/i.test(c.html)) tells.push("Unsplash stock hero");
    if (/<title>\s*(?:create next app|next\.js app|vite \+ react|react app)\s*<\/title>/i.test(c.html))
      tells.push("untouched starter <title>");
    if (!tells.length) return null;
    return {
      id: "stock-assets",
      label: "Stock / placeholder assets & untouched starter metadata",
      category: "placeholder",
      points: Math.min(4, tells.length * 2),
      evidence: ev(tells),
    };
  },
];

const ALL_DETECTORS: Detector[] = [
  ...watermarkDetectors,
  ...stackDetectors,
  ...copyDetectors,
  ...structureDetectors,
  ...visualDetectors,
  ...placeholderDetectors,
];

/** Strip tags/scripts/styles to approximate visible text. */
function extractText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function pickVerdict(score: number): Verdict {
  if (score <= 18)
    return { label: "Suspiciously Human", emoji: "🧑‍🎨", blurb: "Bespoke and opinionated. A real person sweated over this." };
  if (score <= 38)
    return { label: "Mostly Handcrafted", emoji: "🛠️", blurb: "Custom work with a few convenient shortcuts. Tasteful." };
  if (score <= 58)
    return { label: "AI-Assisted", emoji: "🤝", blurb: "A human and a model clearly co-wrote this one." };
  if (score <= 78)
    return { label: "Heavily AI-Generated", emoji: "🤖", blurb: "The agent did most of the driving. Few human fingerprints." };
  return { label: "Textbook AI Slop", emoji: "🪐", blurb: "Default skill, default stack, default everything. Peak vibe-code." };
}

export function analyze(
  html: string,
  headers: Record<string, string>,
  url: string,
  finalUrl: string
): AnalysisResult {
  const lower = html.toLowerCase();
  const text = extractText(html);
  const ctx: Ctx = { html, lower, text, headers, url };

  const signals: Signal[] = [];
  for (const d of ALL_DETECTORS) {
    try {
      const s = d(ctx);
      if (s && s.points > 0) signals.push(s);
    } catch {
      // a single detector blowing up should never sink the analysis
    }
  }

  // Aggregate per-category, capping each category at its max so no single
  // dimension can run away with the score.
  const categories: CategoryScore[] = (Object.keys(CATEGORY_META) as SignalCategory[]).map((cat) => {
    const catSignals = signals.filter((s) => s.category === cat);
    const raw = catSignals.reduce((sum, s) => sum + s.points, 0);
    const meta = CATEGORY_META[cat];
    return {
      category: cat,
      title: meta.title,
      emoji: meta.emoji,
      points: Math.min(raw, meta.max),
      max: meta.max,
      signals: catSignals.sort((a, b) => b.points - a.points),
    };
  });

  const score = Math.max(
    0,
    Math.min(100, Math.round(categories.reduce((sum, c) => sum + c.points, 0)))
  );

  const titleMatch = html.match(/<title[^>]*>([^<]*)<\/title>/i);
  const genMatch = html.match(/<meta[^>]+name=["']generator["'][^>]+content=["']([^"']+)["']/i);

  return {
    url,
    finalUrl,
    score,
    verdict: pickVerdict(score),
    categories: categories.sort((a, b) => b.points - a.points),
    topSignals: [...signals].sort((a, b) => b.points - a.points).slice(0, 5),
    meta: {
      title: titleMatch ? titleMatch[1].trim().slice(0, 120) : null,
      generator: genMatch ? genMatch[1] : null,
      bytes: html.length,
      fetchedAt: new Date().toISOString(),
    },
  };
}
